### PR TITLE
Static analysis

### PR DESCRIPTION
**Pull request by poldy**
I may have gone overboard but I was curious about how far compiler warnings and static analysis can take you. I didn't add any new features (fixed a few bugs though). In particular, there's a risk that I've broken Windows builds, although it's easy to install a Linux subsystem from that OS's App Store nowadays anyway. I did test on macOS & ARM Linux.

If you're reluctant, please feel free to discuss.

### CODE REVIEW

**Comment by pietsch** [comment]
Wow, you seem to enjoy cleaning up this old code! The downside is that I no longer understand what you are doing here – I never really wrote a program in COMAL, and my C(++) day are long gone. Would you like to take over as the maintainer of this little project?

**Comment by poldy** [comment]
I may have to maintain some old proprietary code at work, and this project is a nice size to do experiments on to try find out what works or not, e.g. I tried a little porting to C++ and that was too hard. I missed out on using COMAL back in the day too (BASIC instead), but it was actually reasonably popular here in Ireland. I do write C for a living however (usually, I'm doing process work for a few months so am using this to keep in practice).

I have no problem taking over, although I may do very little more with it. On the other hand, from the commit log it's a very quiet project that shouldn't take much time. The only practical step I know of for this would be to change the "fork" hyperlink on the Wikipedia page?

**Comment by pietsch** [comment]
I guess so. Feel free to go ahead. Or I can edit the Wikipedia page if you like.

**Comment by poldy** [comment]
It's ok, I just did that now, thanks.

If you could change the description on the front page of your clone to refer people there too that would be great, but I don't know github well enough to know if it's possible. If not, don't worry about it.

**Pull request closed without merging**
